#!/usr/bin/env bash

# Git log
alias log="git log --graph --pretty=format:'%Cred%h%Creset %C(cyan)%an%Creset -%C(blue)%d%Creset %s %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"

# File system
alias ls='ls -lh --group-directories-first --color=auto'
alias lsa='ls -a'
alias lt='tree -L 2'
alias lta='tree -a -L 2'
alias ff="fzf --preview 'cat {}'"
alias cd="zd"

zd() {
  if [ $# -eq 0 ]; then
    builtin cd ~ && return
  elif [ -d "$1" ]; then
    builtin cd "$1"
  else
    z "$@" && printf " \U000F17A9 " && pwd || echo "Error: Directory not found"
  fi
}

# Directories
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
