#!/usr/bin/env bash

prompt_git() {
	local branchColor=$1;
	local branchName='';

	# Check if the current directory is in a Git repository.
	git rev-parse --is-inside-work-tree &>/dev/null || return;

	# Check for what branch we’re on.
	# Get the short symbolic ref. If HEAD isn’t a symbolic ref, get a
	# tracking remote branch or tag. Otherwise, get the
	# short SHA for the latest commit, or give up.
	branchName="$(git symbolic-ref --quiet --short HEAD 2> /dev/null || \
		git describe --all --exact-match HEAD 2> /dev/null || \
		git rev-parse --short HEAD 2> /dev/null || \
		echo '(unknown)')";

	# Check for uncommitted changes in the index.
	if ! $(git diff --quiet --ignore-submodules --cached); then
		branchColor=$2;
	fi;

	# Check for unstaged changes.
	if ! $(git diff-files --quiet --ignore-submodules --); then
		branchColor=$2;
	fi;
	# Check for untracked files.
	if [ -n "$(git ls-files --others --exclude-standard)" ]; then
		branchColor=$2;
	fi;

	[ -n "${s}" ] && s=" [${s}]";

	echo -e "${branchColor}[${branchName}]";
}

if tput setaf 1 &> /dev/null; then
	tput sgr0; # reset colors
	bold=$(tput bold);
	reset=$(tput sgr0);
	black=$(tput setaf 0);
	blue=$(tput setaf 33);
	cyan=$(tput setaf 37);
	green=$(tput setaf 2);
	orange=$(tput setaf 3);
	purple=$(tput setaf 5);
	red=$(tput setaf 1);
	violet=$(tput setaf 5);
	white=$(tput setaf 7);
	yellow=$(tput setaf 3);
else
	bold='\033[1m';
	reset='\033[0m';
	black='\033[0;30m';
	blue='\033[0;34m';
	cyan='\033[0;36m';
	green='\033[0;32m';
	orange='\033[0;33m';
	purple='\033[0;35m';
	red='\033[0;31m';
	violet='\033[0;35m';
	white='\033[0;37m';
	yellow='\033[0;33m';
fi;

# Highlight the user name when logged in as root.
if [[ "${USER}" == "root" ]]; then
	userStyle="${red}";
else
	userStyle="${yellow}";
fi;

# Highlight the hostname when connected via SSH.
if [[ "${SSH_TTY}" ]]; then
	hostStyle="${bold}${red}";
else
	hostStyle="${yellow}";
fi;

# Set the terminal title and prompt.

PS1="\[\033]0;\W\007\]"; # working directory base name
PS1+="\[${bold}\]\n"; # newline
PS1+="\[${userStyle}\]\u@"; # username
PS1+="\[${hostStyle}\]\h "; # host
PS1+="\[${blue}\]\w"; # working directory full path

PS1+="\$(prompt_git \"\[${white}\]\[${green}\]\" \"\[${red}\]\")"; # Git repository details
PS1+="\[${white}\] \$ \[${reset}\]"; # `$` (and reset color)
export PS1;

PS2="\[${yellow}\]→ \[${reset}\]";
export PS2;
