#!/usr/bin/env bash

prompt_git() {
	local branchColor=$1;
	local branchName='';

	# Check if the current directory is in a Git repository.
	git rev-parse --is-inside-work-tree &>/dev/null || return;

	# Check for what branch we’re on.
	# Get the short symbolic ref. If HEAD isn’t a symbolic ref, get a
	# tracking remote branch or tag. Otherwise, get the
	# short SHA for the latest commit, or give up.
	branchName="$(git symbolic-ref --quiet --short HEAD 2> /dev/null || \
		git describe --all --exact-match HEAD 2> /dev/null || \
		git rev-parse --short HEAD 2> /dev/null || \
		echo '(unknown)')";

	# Check for uncommitted changes in the index.
	if ! $(git diff --quiet --ignore-submodules --cached); then
		branchColor=$2;
	fi;

	# Check for unstaged changes.
	if ! $(git diff-files --quiet --ignore-submodules --); then
		branchColor=$2;
	fi;
	# Check for untracked files.
	if [ -n "$(git ls-files --others --exclude-standard)" ]; then
		branchColor=$2;
	fi;

	[ -n "${s}" ] && s=" [${s}]";

	echo -e "${branchColor}[${branchName}]";
}

if tput setaf 1 &> /dev/null; then
	tput sgr0; # reset colors
	bold=$(tput bold);
	reset=$(tput sgr0);
	black=$(tput setaf 0);
	blue=$(tput setaf 75);
	cyan=$(tput setaf 37);
	green=$(tput setaf 71);
	orange=$(tput setaf 166);
	purple=$(tput setaf 125);
	red=$(tput setaf 210);
	violet=$(tput setaf 183);
	white=$(tput setaf 15);
	yellow=$(tput setaf 178);
else
	bold='';
	reset="\e[0m";
	black="\e[1;30m";
	blue="\e[1;34m";
	cyan="\e[1;36m";
	green="\e[1;32m";
	orange="\e[1;33m";
	purple="\e[1;35m";
	red="\e[1;31m";
	violet="\e[1;35m";
	white="\e[1;37m";
	yellow="\e[1;33m";
fi;

# Highlight the user name when logged in as root.
if [[ "${USER}" == "root" ]]; then
	userStyle="${red}";
else
	userStyle="${yellow}";
fi;

# Highlight the hostname when connected via SSH.
if [[ "${SSH_TTY}" ]]; then
	hostStyle="${bold}${red}";
else
	hostStyle="${yellow}";
fi;

# Set the terminal title and prompt.

PS1="\[\033]0;\W\007\]"; # working directory base name
PS1+="\[${bold}\]\n"; # newline
PS1+="\[${userStyle}\]\u@"; # username
PS1+="\[${hostStyle}\]\h "; # host
PS1+="\[${blue}\]\w"; # working directory full path

PS1+="\$(prompt_git \"\[${white}\]\[${green}\]\" \"\[${red}\]\")"; # Git repository details
PS1+="\[${white}\] \$ \[${reset}\]"; # `$` (and reset color)
export PS1;

PS2="\[${yellow}\]→ \[${reset}\]";
export PS2;
